--- 
javascripts: 
- base: 
  - jquery-1.3.1.min.js
  - jquery-ui-1.7.1.custom.min.js
  - jquery.tools.min.js
  - cufon.js
  - museo-sans.font.js
  - screen.js
  - jrails
  - application
stylesheets: 
- base: 
  - reset
  - typography
  - grid
  - forms
  - site
- homepage:
  - reset
  - screen
- ie:
  - ie


