--- 
javascripts: 
- base: 
  - jquery-1.3.1.min
  - jquery-ui-1.7.1.custom.min
  - jquery.tools.min
  - cufon
  - museo-sans.font
  - screen
  - jrails
  - application
stylesheets: 
- base: 
  - reset
  - typography
  - grid
  - forms
  - site
- homepage:
  - reset
  - screen
- ie:
  - ie


