--- 
javascripts: 
- base: 
  - jquery-1.3.2.min
  - jquery-ui-1.7.1.custom.min
  - jquery.corners.min
  - jrails
  - application
stylesheets: 
- base: 
  - reset
  - typography
  - grid
  - forms
  - site
- homepage:
  - reset
  - typography
  - grid
  - forms
  - site
  - homepage
- ie:
  - ie
